/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ebs;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yi Qing Tan
 */
public class DeleteData extends javax.swing.JFrame {

    /**
     * Creates new form DeleteData
     * @throws java.io.FileNotFoundException
     */
    Sort srt=new Sort();
    Search sch=new Search();
    int index;
    ViewData vd=new ViewData();
    public DeleteData() throws FileNotFoundException {
        initComponents();
        
        setIconImage();
        
        ImageIcon stf=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Stafficon.png")));
        Image stf1=stf.getImage();
        Image stf2=stf1.getScaledInstance(staff.getWidth(),staff.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon s=new ImageIcon(stf2);
        staff.setIcon(s);
        ImageIcon bck=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("BackButton.png")));
        Image bck1=bck.getImage();
        Image bck2=bck1.getScaledInstance(backBtn.getWidth(), backBtn.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon b= new ImageIcon(bck2);
        backBtn.setIcon(b);
        ImageIcon home=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("HomeButton.png")));
        Image home1=home.getImage();
        Image home2=home1.getScaledInstance(homeBtn.getWidth(), homeBtn.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon h= new ImageIcon(home2);
        homeBtn.setIcon(h);
        ImageIcon cs=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("customerservice.png")));
        Image cs1=cs.getImage();
        Image cs2=cs1.getScaledInstance(csBtn.getWidth(), csBtn.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon c= new ImageIcon(cs2);
        csBtn.setIcon(c);
        
        //Table
        
        //vd.loadUserList();
        

        DefaultTableModel tmd=(DefaultTableModel)datatable.getModel();
        Object rowData[]=new Object[11];
       
            for(int i=0;i<vd.userRec.size();i++){
            rowData[0]=vd.userRec.get(i).getaN();
            rowData[1]=vd.userRec.get(i).getiN();
            rowData[2]=vd.userRec.get(i).getDate();
            rowData[3]=vd.userRec.get(i).getnm();
            rowData[4]=vd.userRec.get(i).getads();
            rowData[5]=vd.userRec.get(i).getmN();
            rowData[6]=vd.userRec.get(i).getpM();
            rowData[7]=vd.userRec.get(i).getcM();
            rowData[8]=vd.userRec.get(i).gettUsage();
            rowData[9]=vd.userRec.get(i).getuBill();
            rowData[10]=vd.userRec.get(i).getcCharge();
            tmd.addRow(rowData);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        staff = new javax.swing.JLabel();
        deletedatatitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        datatable = new javax.swing.JTable();
        delBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JLabel();
        homeBtn = new javax.swing.JLabel();
        csBtn = new javax.swing.JLabel();
        searchtitle = new javax.swing.JLabel();
        searchtxt = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Electricity Billing System");

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setForeground(new java.awt.Color(255, 255, 51));

        staff.setText("Staff");

        deletedatatitle.setFont(new java.awt.Font("Adobe Gothic Std B", 1, 48)); // NOI18N
        deletedatatitle.setText("Delete Data");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(staff, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deletedatatitle, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staff, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletedatatitle, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        datatable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account Number", "Invois Number", "Date", "Name", "Address", "Meter Number", "Previous Meter", "Current Meter", "Total Usage", "Previous Unpaid Bill(RM)", "Current Charge(RM)"
            }
        ));
        jScrollPane2.setViewportView(datatable);

        delBtn.setBackground(new java.awt.Color(255, 0, 0));
        delBtn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        delBtn.setForeground(new java.awt.Color(255, 255, 255));
        delBtn.setText("Delete");
        delBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delBtnMouseClicked(evt);
            }
        });

        backBtn.setText("jLabel8");
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });

        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
        });

        csBtn.setText("jLabel10");

        searchtitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchtitle.setText("Search:");

        searchtxt.setText("Account Number or Name");
        searchtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchtxtMouseClicked(evt);
            }
        });

        searchbtn.setBackground(new java.awt.Color(51, 51, 255));
        searchbtn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        searchbtn.setForeground(new java.awt.Color(255, 255, 255));
        searchbtn.setText("Search");
        searchbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchbtnMouseClicked(evt);
            }
        });

        clearbtn.setBackground(new java.awt.Color(255, 51, 51));
        clearbtn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        clearbtn.setForeground(new java.awt.Color(255, 255, 255));
        clearbtn.setText("Clear");
        clearbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(591, 591, 591)
                        .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(csBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 1344, Short.MAX_VALUE)
                                .addComponent(delBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(486, 486, 486)
                .addComponent(searchtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchtitle)
                    .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchbtn)
                    .addComponent(clearbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(delBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(csBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
       
    private void delBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delBtnMouseClicked
        
        int response=JOptionPane.showConfirmDialog(rootPane,"Confirm Delete", "Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(response==JOptionPane.YES_OPTION){
        try{
        DefaultTableModel table=(DefaultTableModel)datatable.getModel();
        
        int row=datatable.getSelectedRow();
        String accNum=(String) datatable.getValueAt(row, 0);
        long aN=Long.parseLong(accNum);
        //srt.BubbleSort(vd.userRec);
        int num=sch.BinarySearch(aN, vd.userRec);
        vd.userRec.remove(num);
        
        table.removeRow(row);
        try{
        FileWriter writer=new FileWriter("User List.txt");
        
        
        for(int i=0;i<vd.userRec.size();i++){
            writer.write(vd.userRec.get(i).getaN()+"#"+vd.userRec.get(i).getiN()+"#"+vd.userRec.get(i).getDate()+"#"+vd.userRec.get(i).getnm()+"#"+vd.userRec.get(i).getads()
                         +"#"+vd.userRec.get(i).getmN()+"#"+vd.userRec.get(i).getcM()+"#"+vd.userRec.get(i).getpM()+"#"+vd.userRec.get(i).gettUsage()+"#"+vd.userRec.get(i).getuBill()
                         +"#"+vd.userRec.get(i).getcCharge()+"\n");
            
        }
        writer.close();
        }catch(IOException e){
            JOptionPane.showMessageDialog(rootPane,"Error");
        }
        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane,"Error");
        }
        }

    }//GEN-LAST:event_delBtnMouseClicked

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        Staff staff=new Staff();
        staff.setVisible(true);
        this.dispose();
        staff.setLocationRelativeTo(null);
    }//GEN-LAST:event_backBtnMouseClicked

    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
        Menu menu=new Menu();
        menu.setVisible(true);
        this.dispose();
        menu.setLocationRelativeTo(null);
    }//GEN-LAST:event_homeBtnMouseClicked

    private void searchtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchtxtMouseClicked
        searchtxt.setText("");
        datatable.setModel(new DefaultTableModel(null, new String[]{"Account Number",
            "Invois Number","Date","Name","Address",
            "Meter Number","Previous Meter","Currenr Meter",
            "Total Usage","Previous Unpaid Bill(RM)","Current Charge(RM)"}));
        DefaultTableModel tmd=(DefaultTableModel)datatable.getModel();
        Object rowData[]=new Object[11];
       
            for(int i=0;i<vd.userRec.size();i++){
            rowData[0]=vd.userRec.get(i).getaN();
            rowData[1]=vd.userRec.get(i).getiN();
            rowData[2]=vd.userRec.get(i).getDate();
            rowData[3]=vd.userRec.get(i).getnm();
            rowData[4]=vd.userRec.get(i).getads();
            rowData[5]=vd.userRec.get(i).getmN();
            rowData[6]=vd.userRec.get(i).getpM();
            rowData[7]=vd.userRec.get(i).getcM();
            rowData[8]=vd.userRec.get(i).gettUsage();
            rowData[9]=vd.userRec.get(i).getuBill();
            rowData[10]=vd.userRec.get(i).getcCharge();
            tmd.addRow(rowData);
            }

    }//GEN-LAST:event_searchtxtMouseClicked

    private void searchbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbtnMouseClicked
        try{
            datatable.setModel(new DefaultTableModel(null, new String[]{"Account Number","Invois Number","Date","Name","Address","Meter Number","Previous Meter","Currenr Meter","Total Usage","Previous Unpaid Bill(RM)","Current Charge(RM)"}));
            try{
                String accNum=searchtxt.getText();
                long aNum=Long.parseLong(accNum);
                srt.BubbleSort(vd.userRec);
                index=sch.BinarySearch(aNum, vd.userRec);
            }catch(NumberFormatException ex){
                String name=searchtxt.getText();
                srt.BubbleSortName(vd.userRec);
                index=sch.BinarySearchName(name,vd.userRec);
                
            }
            System.out.print(index);
            DefaultTableModel md=(DefaultTableModel)datatable.getModel();

            Object row[]=new Object[11];
            row[0]=vd.userRec.get(index).getaN();
            row[1]=vd.userRec.get(index).getiN();
            row[2]=vd.userRec.get(index).getDate();
            row[3]=vd.userRec.get(index).getnm();
            row[4]=vd.userRec.get(index).getads();
            row[5]=vd.userRec.get(index).getmN();
            row[6]=vd.userRec.get(index).getpM();
            row[7]=vd.userRec.get(index).getcM();
            row[8]=vd.userRec.get(index).gettUsage();
            row[9]=vd.userRec.get(index).getuBill();
            row[10]=vd.userRec.get(index).getcCharge();
            md.addRow(row);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Data not found");
        }
    }//GEN-LAST:event_searchbtnMouseClicked

    private void clearbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearbtnMouseClicked
        try{
            DefaultTableModel tm=(DefaultTableModel)datatable.getModel();
            tm.removeRow(0);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "No data to be clear");
        }
    }//GEN-LAST:event_clearbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DeleteData().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(DeleteData.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backBtn;
    private javax.swing.JButton clearbtn;
    private javax.swing.JLabel csBtn;
    private javax.swing.JTable datatable;
    private javax.swing.JButton delBtn;
    private javax.swing.JLabel deletedatatitle;
    private javax.swing.JLabel homeBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton searchbtn;
    private javax.swing.JLabel searchtitle;
    private javax.swing.JTextField searchtxt;
    private javax.swing.JLabel staff;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    }
    
    
   
}

