/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ebs;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author Yi Qing Tan
 */
public class Guest extends javax.swing.JFrame {

    /**
     * Creates new form Guest
     */
    public Guest() {
        initComponents();
        setIconImage();
        
        //Guest Logo
        ImageIcon guest=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("guest.png")));
        Image img1=guest.getImage();
        Image img2=img1.getScaledInstance(guestIcon.getWidth(), guestIcon.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon g=new ImageIcon(img2);
        guestIcon.setIcon(g);    
        
        //Calculator Logo
        ImageIcon cal=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("calculator.png")));
        Image cal1=cal.getImage();
        Image cal2=cal1.getScaledInstance(billcalculator.getWidth(),billcalculator.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon c=new ImageIcon(cal2);
        billcalculator.setIcon(c);
        
        //Bill Logo
        ImageIcon bil=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("checkbill.png")));
        Image bil1=bil.getImage();
        Image bil2=bil1.getScaledInstance(checkbill1.getWidth(), checkbill1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon b=new ImageIcon(bil2);
        checkbill1.setIcon(b);
        
        //PayBill Logo
        ImageIcon payBill=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("bill.png")));
        Image payBill1=payBill.getImage();
        Image payBill2=payBill1.getScaledInstance(payment1.getWidth(), payment1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon pB=new ImageIcon(payBill2);
        payment1.setIcon(pB);
        
        //BackButton Logo
        ImageIcon back=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("backbutton.png")));
        Image back1=back.getImage();
        Image back2=back1.getScaledInstance(backBtn.getWidth(),backBtn.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon b1=new ImageIcon(back2);
        backBtn.setIcon(b1);
        
        //HomeButton Logo
        ImageIcon home=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("HomeButton.png")));
        Image home1=home.getImage();
        Image home2=home1.getScaledInstance(homeBtn.getWidth(),homeBtn.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon h=new ImageIcon(home2);
        homeBtn.setIcon(h);
        
        ImageIcon cs=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("customerService.png")));
        Image cs1=cs.getImage();
        Image cs2=cs1.getScaledInstance(customerservice.getWidth(),customerservice.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon cs3=new ImageIcon(cs2);
        customerservice.setIcon(cs3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        guestIcon = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        billcalculatorpanel = new javax.swing.JPanel();
        billcalculator1 = new javax.swing.JLabel();
        billcalculator = new javax.swing.JLabel();
        paymentpanel = new javax.swing.JPanel();
        payment = new javax.swing.JLabel();
        payment1 = new javax.swing.JLabel();
        checkbillpanel = new javax.swing.JPanel();
        checkbill = new javax.swing.JLabel();
        checkbill1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JLabel();
        homeBtn = new javax.swing.JLabel();
        customerservice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Electricity Billing System");

        jPanel2.setBackground(new java.awt.Color(255, 255, 51));
        jPanel2.setForeground(new java.awt.Color(255, 255, 51));

        guestIcon.setText("Guest");

        title.setFont(new java.awt.Font("Adobe Gothic Std B", 1, 48)); // NOI18N
        title.setText("Guest");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guestIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guestIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        billcalculatorpanel.setBackground(new java.awt.Color(255, 153, 153));
        billcalculatorpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        billcalculatorpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billcalculatorpanelMouseClicked(evt);
            }
        });

        billcalculator1.setFont(new java.awt.Font("News701 BT", 1, 24)); // NOI18N
        billcalculator1.setText("Bill Calculator");
        billcalculator1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billcalculator1MouseClicked(evt);
            }
        });

        billcalculator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billcalculatorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout billcalculatorpanelLayout = new javax.swing.GroupLayout(billcalculatorpanel);
        billcalculatorpanel.setLayout(billcalculatorpanelLayout);
        billcalculatorpanelLayout.setHorizontalGroup(
            billcalculatorpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billcalculatorpanelLayout.createSequentialGroup()
                .addGroup(billcalculatorpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(billcalculator1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(billcalculator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        billcalculatorpanelLayout.setVerticalGroup(
            billcalculatorpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billcalculatorpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(billcalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(billcalculator1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paymentpanel.setBackground(new java.awt.Color(153, 255, 153));
        paymentpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        paymentpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paymentpanelMouseClicked(evt);
            }
        });

        payment.setFont(new java.awt.Font("News701 BT", 1, 24)); // NOI18N
        payment.setText("Bill Payment");
        payment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paymentMouseClicked(evt);
            }
        });

        payment1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payment1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout paymentpanelLayout = new javax.swing.GroupLayout(paymentpanel);
        paymentpanel.setLayout(paymentpanelLayout);
        paymentpanelLayout.setHorizontalGroup(
            paymentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(payment, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(payment1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        paymentpanelLayout.setVerticalGroup(
            paymentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentpanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(payment1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(payment)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        checkbillpanel.setBackground(new java.awt.Color(153, 153, 255));
        checkbillpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        checkbillpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkbillpanelMouseClicked(evt);
            }
        });

        checkbill.setFont(new java.awt.Font("News701 BT", 1, 24)); // NOI18N
        checkbill.setText("Check Bill");
        checkbill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkbillMouseClicked(evt);
            }
        });

        checkbill1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkbill1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout checkbillpanelLayout = new javax.swing.GroupLayout(checkbillpanel);
        checkbillpanel.setLayout(checkbillpanelLayout);
        checkbillpanelLayout.setHorizontalGroup(
            checkbillpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkbillpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkbill, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(checkbill1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        checkbillpanelLayout.setVerticalGroup(
            checkbillpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkbillpanelLayout.createSequentialGroup()
                .addComponent(checkbill1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkbill)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        backBtn.setText("jLabel8");
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });

        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
        });

        customerservice.setText("jLabel10");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(205, 205, 205)
                        .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(customerservice, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(billcalculatorpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(checkbillpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(paymentpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(billcalculatorpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkbillpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerservice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void billcalculatorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billcalculatorMouseClicked
        BillCalculator bc=new BillCalculator();
        bc.setVisible(true);
        bc.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_billcalculatorMouseClicked

    private void billcalculatorpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billcalculatorpanelMouseClicked
        BillCalculator bc=new BillCalculator();
        bc.setVisible(true);
        bc.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_billcalculatorpanelMouseClicked

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        Menu menu=new Menu();
        menu.setVisible(true);
        this.dispose();
        menu.setLocationRelativeTo(null);
    }//GEN-LAST:event_backBtnMouseClicked

    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
        Menu menu=new Menu();
        menu.setVisible(true);
        this.dispose();
        menu.setLocationRelativeTo(null);
    }//GEN-LAST:event_homeBtnMouseClicked

    private void checkbill1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkbill1MouseClicked
        CheckBill cb=new CheckBill();
        cb.setVisible(true);
        this.dispose();
        cb.setLocationRelativeTo(null);
    }//GEN-LAST:event_checkbill1MouseClicked

    private void checkbillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkbillMouseClicked
        CheckBill cb=new CheckBill();
        cb.setVisible(true);
        this.dispose();
        cb.setLocationRelativeTo(null);
    }//GEN-LAST:event_checkbillMouseClicked

    private void checkbillpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkbillpanelMouseClicked
        CheckBill cb=new CheckBill();
        cb.setVisible(true);
        this.dispose();
        cb.setLocationRelativeTo(null);
    }//GEN-LAST:event_checkbillpanelMouseClicked

    private void payment1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payment1MouseClicked
        Payment cb=new Payment();
        cb.setVisible(true);
        this.dispose();
        cb.setLocationRelativeTo(null);
    }//GEN-LAST:event_payment1MouseClicked

    private void paymentpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentpanelMouseClicked
        Payment cb=new Payment();
        cb.setVisible(true);
        this.dispose();
        cb.setLocationRelativeTo(null);
    }//GEN-LAST:event_paymentpanelMouseClicked

    private void paymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentMouseClicked
        Payment cb=new Payment();
        cb.setVisible(true);
        this.dispose();
        cb.setLocationRelativeTo(null);
    }//GEN-LAST:event_paymentMouseClicked

    private void billcalculator1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billcalculator1MouseClicked
        BillCalculator bc=new BillCalculator();
        bc.setVisible(true);
        bc.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_billcalculator1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backBtn;
    private javax.swing.JLabel billcalculator;
    private javax.swing.JLabel billcalculator1;
    private javax.swing.JPanel billcalculatorpanel;
    private javax.swing.JLabel checkbill;
    private javax.swing.JLabel checkbill1;
    private javax.swing.JPanel checkbillpanel;
    private javax.swing.JLabel customerservice;
    private javax.swing.JLabel guestIcon;
    private javax.swing.JLabel homeBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel payment;
    private javax.swing.JLabel payment1;
    private javax.swing.JPanel paymentpanel;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    }
}
